# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: massa2000
  host: localhost
  port: 5432


development:
  <<: *default
  database: blogapp

test:
  <<: *default
  database: blogapp_test


production:
  <<: *default
  database: blogapp_production
  username: postgres    
  password: massa2000
  host: localhost